### ISSUE TITLE
module 'torchvision.models' has no attribute 'segmentation'

### ISSUE THREAD

**Issue by Bralio123** [pytorch/vision#2062]
## To Reproduce

1. Import segmentation models from torchvision segmentation folders 

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 417.22
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] numpydoc==0.9.1
[pip] torch==1.0.1
[pip] torchfcn==1.9.3
[pip] torchsummary==1.5.1
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] cuda100                   1.0                           0    pytorch
[conda] cudatoolkit               10.0.130                      0  
[conda] mkl                       2019.4                      245  
[conda] mkl-service               2.0.2            py36he774522_0  
[conda] mkl_fft                   1.0.14           py36h14836fe_0  
[conda] mkl_random                1.0.2            py36h343c172_0  
[conda] numpy                     1.16.4           py36h19fb1c0_0  
[conda] numpy-base                1.16.4           py36hc3f5095_0  
[conda] numpydoc                  0.9.1                      py_0  
[conda] pytorch                   1.0.1           py3.6_cuda100_cudnn7_1    pytorch
[conda] torchfcn                  1.9.3                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.2.1                    pypi_0    pypi

Process finished with exit code 0

**Comment by Bralio123** [comment]
Sorry if this is incomplete. I am struggling to simply import models from the torchvision package as the error states. I have removed and downloaded the most up to date packages (both torch and torchvision)

**Comment by pmeier** [comment]
I'm guessing you want to load for example `fcn_resnet101` or `deeplabv3_resnet101` as can be seen in the [reference segmentation](https://github.com/pytorch/vision/tree/master/references/segmentation), correct? If that is the case you should do something like this:

```python
from torchvision.models import segmentation

model = segmentation.fcn_resnet101(...)
```

Is that what you wanted to do? If not, could you please share the code that you think contains a bug.

https://github.com/pytorch/vision/tree/master/references/segmentation

**Comment by bhobley** [comment]
Yes, that's exactly what I was trying to do. 

model = torchvision.models.segmentation.deeplabv3_resnet50()

error:
model = torchvision.models.segmentation.deeplabv3_resnet50()
AttributeError: module 'torchvision.models' has no attribute 'segmentation'

**Comment by pmeier** [comment]
@Bralio123 @bhobley Are you the same person or am I talking to two individuals here?

---

The snippet you posted works fine for me with `torch==1.4.0` and `torchvision==0.5.0`. I'm guessing you use old versions that do net yet implement the segmentation models. `torchvision.models.segmentation` is available for `torchvision>=0.3.0`. 

From your first comment it seems you are using `torchvision==0.2.2` which does not satisfy the requirement. You simply need to update to `torch` and `torchvision` to solve your problem.

**Comment by Bralio123** [comment]
Yes, both accounts are the same person. No clue how that happened.

Thanks, that worked!

**Comment by fmassa** [comment]
Thanks @pmeier for the help!

**Comment by mohammad-brdrn** [comment]
set your torch version to 1.4.0 and then upgrade your torchvision to 0.5.0
