### ISSUE TITLE
ops.deform_conv2d causes CUDA illegal memory access

### ISSUE THREAD

**Issue by godspeed1989** [pytorch/vision#2598]
## 🐛 Bug
I try to test the speed of deformable conv2d. But always encountered memory error.

## To Reproduce

```
$ ipython
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch
   ...: import torchvision as tv
   ...: weight = torch.randn(9,9,3,3).cuda()
   ...: weight.requires_grad = True
   ...: img = torch.randn(8, 9, 1000, 110).cuda()
   ...: def test():
   ...:     offset = torch.randn(8,18,1000,110).cuda()
   ...:     out = tv.ops.deform_conv2d(img, offset, weight, padding=1)
   ...:     out.mean().backward()
   ...: 

In [2]: import os

In [3]: os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

In [4]: timeit test()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-a1086d7a4706> in <module>
----> 1 get_ipython().run_line_magic('timeit', 'test()')

/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2324                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2325             with self.builtin_trap:
-> 2326                 result = fn(*args, **kwargs)
   2327             return result
   2328 

<decorator-gen-60> in timeit(self, line, cell, local_ns)

/usr/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/usr/lib/python3.8/site-packages/IPython/core/magics/execution.py in timeit(self, line, cell, local_ns)
   1171                     break
   1172 
-> 1173         all_runs = timer.repeat(repeat, number)
   1174         best = min(all_runs) / number
   1175         worst = max(all_runs) / number

/usr/lib/python3.8/timeit.py in repeat(self, repeat, number)
    203         r = []
    204         for i in range(repeat):
--> 205             t = self.timeit(number)
    206             r.append(t)
    207         return r

/usr/lib/python3.8/site-packages/IPython/core/magics/execution.py in timeit(self, number)
    167         gc.disable()
    168         try:
--> 169             timing = self.inner(it, self.timer)
    170         finally:
    171             if gcold:

<magic-timeit> in inner(_it, _timer)

<ipython-input-1-a97200bb984a> in test()
      5 img = torch.randn(8, 9, 1000, 110).cuda()
      6 def test():
----> 7     offset = torch.randn(8,18,1000,110).cuda()
      8     out = tv.ops.deform_conv2d(img, offset, weight, padding=1)
      9     out.mean().backward()

RuntimeError: CUDA error: an illegal memory access was encountered

In [5]: 
```

## Environment
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 11.0

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.1.0
Clang version: 10.0.1 
CMake version: version 3.18.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.2
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 450.57
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.2
/usr/lib/libcudnn_adv_infer.so.8.0.2
/usr/lib/libcudnn_adv_train.so.8.0.2
/usr/lib/libcudnn_cnn_infer.so.8.0.2
/usr/lib/libcudnn_cnn_train.so.8.0.2
/usr/lib/libcudnn_ops_infer.so.8.0.2
/usr/lib/libcudnn_ops_train.so.8.0.2

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torch-cluster==1.4.5
[pip3] torch-geometric==1.3.2
[pip3] torch-scatter==1.4.0
[pip3] torch-sparse==0.4.3
[pip3] torchvision==0.7.0a0
[conda] Could not collect

**Comment by fmassa** [comment]
Hi,

Thanks for the report.

I just tried your snippet on my machine (using PyTorch 1.7.0.dev20200727 and torchvision from source id 0.8.0a0+1aef87d) and it worked fine.

Can you double-check that the version of PyTorch and torchvision that you are using in your Python interpreter are indeed 1.6.0 and 0.7.0 ? The 0.7.0a0 is a bit suspicious, and is maybe an RC candidate for torchvision.

**Comment by godspeed1989** [comment]
That's weired.
I changed a machine and used a nightly build. But still has the same problem.
```
Collecting environment information...
PyTorch version: 1.7.0.dev20200819
Is debug build: False
CUDA used to build PyTorch: 10.2
OS: Arch Linux (x86_64)
GCC version: (GCC) 10.1.0
Clang version: 10.0.1 
CMake version: version 3.18.1
Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 450.57
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.2
/usr/lib/libcudnn_adv_infer.so.8.0.2
/usr/lib/libcudnn_adv_train.so.8.0.2
/usr/lib/libcudnn_cnn_infer.so.8.0.2
/usr/lib/libcudnn_cnn_train.so.8.0.2
/usr/lib/libcudnn_ops_infer.so.8.0.2
/usr/lib/libcudnn_ops_train.so.8.0.2
Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.7.0.dev20200819
[pip3] torch-cluster==1.4.5
[pip3] torch-geometric==1.3.2
[pip3] torch-scatter==1.4.0
[pip3] torch-sparse==0.4.3
[pip3] torchvision==0.8.0.dev20200820
[conda] Could not collect
```

**Comment by godspeed1989** [comment]
However, if i set the Batch size of test data to 1, everything is fine.

**Comment by fmassa** [comment]
This is what I tried. The only difference was that I set `requires_grad` inside tensor creation (this was an experiment on CPU, I also tried one on CUDA)

```python
In [1]: import torch

In [2]: import torchvision as tv

In [3]: weight = torch.randn(9,9,3,3, requires_grad=True)

In [4]: img = torch.randn(8, 9, 20, 30)

In [5]: def test():
   ...:     offset = torch.randn(8,18,20,30)
   ...:     out = tv.ops.deform_conv2d(img, offset, weight, padding=1)
   ...:     out.mean().backward()
   ...:

In [6]: test()

In [7]: test()

In [8]: test()

In [9]: test()

In [10]: test()

In [11]: test()
```

@vfdev-5 can you try seeing if you can reproduce this issue?

**Comment by vfdev-5** [comment]
@fmassa @godspeed1989 I could reproduce the exception on CUDA by calling twice `test()`
```python
import torch
import torchvision as tv

print(torch.__version__, tv.__version__, torch.version.cuda)

weight = torch.randn(9,9,3,3).cuda()
weight.requires_grad = True
img = torch.randn(8, 9, 1000, 110).cuda()

def test():
    offset = torch.randn(8,18,c).cuda()
    out = tv.ops.deform_conv2d(img, offset, weight, padding=1)
    out.mean().backward()
    
    
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"


test()
test()

> 1.6.0 0.7.0 10.2
> RuntimeError: CUDA error: an illegal memory access was encountered
```

Seems like error is input size dependent (no error with 110x110 input) and if we comment out `out.mean().backward()` code runs without any issue event with `timeit`.

**Comment by vfdev-5** [comment]
@ngimel thanks a lot for the example of how to fetch max grid size !

**Comment by godspeed1989** [comment]
I use the latest torchvision and compliled it as torchvision-0.8.0a0+ac3ba94-cp38-cp38-linux_x86_64.whl.
But I still encounter the illegal memory access problem after several hours of training.
![image](https://user-images.githubusercontent.com/2350713/92142057-ddd37b80-ee45-11ea-8800-45e9b5c12471.png)

The training of my model is fine before I modified several traditional conv layers to deform conv.
Can anyone provide some advice to deal with such a problem?

**Comment by vfdev-5** [comment]
@godspeed1989 maybe some Nans appeared... It is difficult to say like that. Can you give more details and maybe a repreducible code snippet ? That would help

**Comment by godspeed1989** [comment]
@vfdev-5 Thanks for replying. I trained the model last night again and encountered the same issues that happened in optimizer.step().
![image](https://user-images.githubusercontent.com/2350713/92193518-223d3680-ee9b-11ea-8b4a-22f4334dfc6c.png)
Here is the code snippet about how i use deform conv
```
class MASConv_deform(nn.Module):
    # Convolution layer for sparse data
    def __init__(self, in_channels, out_channels, stride=1, bias=True):
        super(MASConv_deform, self).__init__()
        self.stride = stride

        self.off_conv = nn.Conv2d(in_channels, 18, 3, 2, 1, bias=False)
        nn.init.constant_(self.off_conv.weight, 0)
        self.off_conv.register_backward_hook(self._set_lr)

        self.conv = tv.ops.DeformConv2d(in_channels, out_channels, 3,
            stride=stride, padding=1, dilation=1, bias=False)

    @staticmethod
    def _set_lr(module, grad_input, grad_output):
        grad_input = (grad_input[i] * 0.1 for i in range(len(grad_input)))
        grad_output = (grad_output[i] * 0.1 for i in range(len(grad_output)))

    def forward(self, x):
        offset = self.off_conv(x)
        x = self.conv(x, offset)
        return x
```
I think it is hard to reproduce as it happens after several hours of training.
And can you provide some advice about how to avoid Nans in training?

**Comment by vfdev-5** [comment]
@godspeed1989 can you provide more info about what model(s) and how you are training with which hyperparameters (lr, lr scheduling etc) ? If I could have this info I could try to launch the training from my side and reproduce the issue ...

What is the purpose of 
```python
    @staticmethod
    def _set_lr(module, grad_input, grad_output):
        grad_input = (grad_input[i] * 0.1 for i in range(len(grad_input)))
        grad_output = (grad_output[i] * 0.1 for i in range(len(grad_output)))
```
According to the images you provided, it looks like the error can happen on 0th or 1st epoch ? So, it could go over the complete dataset without any issue, right ?

**Comment by godspeed1989** [comment]
I sorry I can't provide the model to you as it is related to an unpublished paper and still under development.
The learning_rate is 1e-3, optimizer is Adam, the weight_decay is 0.
It can go over the dataset at my 2nd attempt.
Now, I am trying to detect if the NaN happens to loss by torch.isnan(). It still fine now.

**Comment by vfdev-5** [comment]
> I sorry I can't provide the model to you as it is related to an unpublished paper and still under development.

@godspeed1989 no worries about that. The dataset is something knowm I assume and there is no corrupted data etc...
Can you check a training mode like overfitting 1-2 batches to see if you model converges etc ?

**Comment by godspeed1989** [comment]
Unfortunately, the program still crashed at the 2nd epoch with the same issue. :(
The evaluation is performed after each epoch on validation set, the model seems converged fine.
May be i should switch to SGD to train it.

**Comment by vfdev-5** [comment]
> Unfortunately, the program still crashed at the 2nd epoch with the same issue. :(
The evaluation is performed after each epoch on validation set, the model seems converged fine.

@godspeed1989 No, I mean reduce the size of your training dataloader to 1-2 batches and try to overfit the model during ~1000 iterations and let's see if it also crashes somewhere and whether it is related to the data somehow...

**Comment by godspeed1989** [comment]
I reduce the size of your training dataloader to 1 batch and train 20000 iterations. The program has finished fine now.

**Comment by Queuecumber** [comment]
Is there any plan to fix this bug? I'm still seeing it above a certain batch size. I assumed this was a manifestation of an out of memory error but I can see that at the largest batch size that works I'm only using 50% of the available GPU memory.

**Comment by vfdev-5** [comment]
@Queuecumber can you provide a code snippet to reproduce your bug ? 
Original bug with deform_conv2d was fixed. Thanks

**Comment by Queuecumber** [comment]
This is what I'm using:

```
class ModulatedDeformConvPack(DeformConv2d):
    def __init__(self, *args, **kwargs):
        super(ModulatedDeformConvPack, self).__init__(*args, **kwargs)

        self.deformable_groups = 1

        self.conv_offset = Conv2d(
            self.in_channels,
            self.deformable_groups * 3 * self.kernel_size[0] * self.kernel_size[1],
            kernel_size=self.kernel_size,
            stride=_pair(self.stride),
            padding=_pair(self.padding),
            dilation=_pair(self.dilation),
            bias=True,
        )

        self.init_offset()

    def init_offset(self):
        self.conv_offset.weight.data.zero_()
        self.conv_offset.bias.data.zero_()

    def forward(self, x):
        out = self.conv_offset(x)
        o1, o2, mask = torch.chunk(out, 3, dim=1)
        offset = torch.cat((o1, o2), dim=1)
        mask = torch.sigmoid(mask)
        return deform_conv2d(input=x, offset=offset, weight=self.weight, stride=_pair(self.stride), padding=_pair(self.padding), dilation=_pair(self.dilation), mask=mask)
```

I can try to make a minimal reproduction, it sounds like it wasnt really fixed because the last reporter had to use a batch size of 1

**Comment by vfdev-5** [comment]
@Queuecumber any updates on producing a minimal reproduction code ?

**Comment by Queuecumber** [comment]
I havent had a change to try it yet

**Comment by Queuecumber** [comment]
I did manage to track down the exact error by using blocking execution:

```
  File "/home/mehrlich/.cache/pypoetry/virtualenvs/fvr-_yTNPG6U-py3.8/lib/python3.8/site-packages/torchvision/ops/deform_conv.py", line 89, in deform_conv2d
    return torch.ops.torchvision.deform_conv2d(
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

It's not particularly informative, I'll try to put together some kind of reproduction today but does this give you any clues about the bug?

**Comment by vfdev-5** [comment]
> It's not particularly informative, I'll try to put together some kind of reproduction today but does this give you any clues about the bug?

Please share your pytorch, torchvision and cuda versions. Will wait for the reproducible code :)

**Comment by Queuecumber** [comment]
The following script produces *an* error but not the exact error from above (although it appears related)

**torchvision_bug.py**
```
from typing import Any

import torch
from torch.nn import Conv2d, LeakyReLU
from torch.nn.modules.utils import _pair
from torchvision.ops import DeformConv2d, deform_conv2d


class ModulatedDeformConvPack(DeformConv2d):
    def __init__(self, *args, offset_channels, deformable_groups: int = 1, post_activation: Any = None, **kwargs):
        super(ModulatedDeformConvPack, self).__init__(*args, **kwargs)

        self.deformable_groups = deformable_groups

        self.conv_offset = Conv2d(
            offset_channels,
            self.deformable_groups * 3 * self.kernel_size[0] * self.kernel_size[1],
            kernel_size=self.kernel_size,
            stride=_pair(self.stride),
            padding=_pair(self.padding),
            dilation=_pair(self.dilation),
            bias=True,
        )

        self.init_offset()

        self.post_activation = post_activation()

    def init_offset(self):
        self.conv_offset.weight.data.zero_()
        self.conv_offset.bias.data.zero_()

    def forward(self, x, m):
        out = self.conv_offset(m)
        o1, o2, mask = torch.chunk(out, 3, dim=1)
        offset = torch.cat((o1, o2), dim=1)
        mask = torch.sigmoid(mask)
        res = deform_conv2d(input=x, offset=offset, weight=self.weight, stride=_pair(self.stride), padding=_pair(self.padding), dilation=_pair(self.dilation), mask=mask)

        if self.post_activation is not None:
            res = self.post_activation(res)

        return res


device = torch.device("cuda")

bs = 23

test_in = torch.randn(bs, 160, 256, 256, device=device)
test_offset = torch.randn(bs, 64, 256, 256, device=device)
dfc = ModulatedDeformConvPack(160, 64, 3, 1, 1, offset_channels=64, deformable_groups=8, post_activation=LeakyReLU).to(device)

print(f"Total memory used before DFC call: {(torch.cuda.max_memory_allocated() / torch.cuda.get_device_properties(device).total_memory) * 100}%")

test_out = dfc(test_in, test_offset)

print(f"Total memory used after DFC call: {(torch.cuda.max_memory_allocated() / torch.cuda.get_device_properties(device).total_memory) * 100}%")

print(test_out.cpu()[0, 0, 0, 0])

```

To reproduce run:

`CUDA_LAUNCH_BLOCKING=1 python torchvision_bug.py` 

Note the variable `bs`. On my test machine I can reproduce at `bs=23` or higher, i.e., `bs=22` works fine, `bs=23` reproduces the error.

I am using a Tesla V100 for testing, this may be related to how much memory the card has, which is why I'm printing the max allocated memory as reported by pytorch. Note that in the working case (22) it's only ~38% on my card so there should be plenty of headroom, although I dont know for sure how accurate that is.

pytorch version: 1.9.0
torchvision version: 0.10.0
cuda version (as reported by nvidia-smi let me know if thats not right): 11.2

**Comment by Queuecumber** [comment]
I also tried on a gtx1080ti but that runs out of memory before I can reproduce the error (I can only get bs up to 18 before it doesn't have enough memory to run the op), it definitely seems related to the way bs is set though, it's not something about how much or fraction of free memory. I think that's all the GPUs I have access to.

Also note this was three different machines and two different IT departments so it's not like its constrained one particular setup (although if you think the bug is in my code that would make things easy to fix)

**Comment by Queuecumber** [comment]
Turns out I do have access to another set of machines with A100 cards, same error, same bs setting, cuda version is 11.4 from the driver this time though and memory usage us only ~15% after the DFC call.

**Comment by vfdev-5** [comment]
Thanks for the code snippet, let me check it from my side and probably we have to open another issue about that. Will get back in a couple of minutes.

**Comment by Queuecumber** [comment]
BTW I think it's not the batch dimension that's the issue but the size of the tensor itself somehow, in my main codebase I was able to reproduce by just using larger images

**Comment by Queuecumber** [comment]
Did you check https://github.com/pytorch/vision/issues/4269 

Summary is try the nightly and see if it's fixed
