### ISSUE TITLE
[bug] Incorrect result when resizing fp16 image with `transform.v2`

### ISSUE THREAD

**Issue by antoinebrl** [pytorch/vision#7727]
### 🐛 Describe the bug

Resizing an fp16 image produces unexpected artifacts and colors when using `tranforms.v2`

Code to reproduce:
```python
import torchvision.transforms as trf1
import torchvision.transforms.v2 as trf2
from torchvision.io import read_image, write_png
import torch

image = read_image("ocean.jpg")

for i, trf in enumerate([trf1, trf2]):
    print(f"\nv{i+1}")
    for dtype in [torch.uint8, torch.float32, torch.float16]:
        print(f"  {dtype}")
        img = trf.ConvertImageDtype(dtype)(image)
        img = trf.Resize((640, 640))(img)
        print(f"    resized,   {img.shape=}, {img.dtype=}, {img.min().item()=}, {img.max().item()=}")

        if i + 1 == 2 and dtype == torch.float16:
            img *= 255
            img = img.to(dtype=torch.uint8)
        else:
            img = trf.ConvertImageDtype(torch.uint8)(img)
        print(f"    converted, {img.shape=}, {img.dtype=}, {img.min().item()=}, {img.max().item()=}")

        write_png(img, f"resized_v{i+1}_{str(dtype)}.png")
```

Output:
```
v1
  torch.uint8
    resized,   img.shape=torch.Size([3, 640, 640]), img.dtype=torch.uint8, img.min().item()=23, img.max().item()=255
    converted, img.shape=torch.Size([3, 640, 640]), img.dtype=torch.uint8, img.min().item()=23, img.max().item()=255
  torch.float32
    resized,   img.shape=torch.Size([3, 640, 640]), img.dtype=torch.float32, img.min().item()=0.0888480469584465, img.max().item()=1.0
    converted, img.shape=torch.Size([3, 640, 640]), img.dtype=torch.uint8, img.min().item()=22, img.max().item()=255
  torch.float16
    resized,   img.shape=torch.Size([3, 640, 640]), img.dtype=torch.float16, img.min().item()=0.0888671875, img.max().item()=1.0
    converted, img.shape=torch.Size([3, 640, 640]), img.dtype=torch.uint8, img.min().item()=0, img.max().item()=255

v2
  torch.uint8
    resized,   img.shape=torch.Size([3, 640, 640]), img.dtype=torch.uint8, img.min().item()=23, img.max().item()=255
    converted, img.shape=torch.Size([3, 640, 640]), img.dtype=torch.uint8, img.min().item()=23, img.max().item()=255
  torch.float32
    resized,   img.shape=torch.Size([3, 640, 640]), img.dtype=torch.float32, img.min().item()=0.0888480544090271, img.max().item()=1.0
    converted, img.shape=torch.Size([3, 640, 640]), img.dtype=torch.uint8, img.min().item()=22, img.max().item()=255
  torch.float16
    resized,   img.shape=torch.Size([3, 640, 640]), img.dtype=torch.float16, img.min().item()=0.0, img.max().item()=1.0
    converted, img.shape=torch.Size([3, 640, 640]), img.dtype=torch.uint8, img.min().item()=0, img.max().item()=255
```

Generated images:

v1 - fp16 | v2 - fp16
:--:|:--:
![resized_v1_torch float16](https://github.com/pytorch/vision/assets/17803473/c5dee7a4-b924-4961-bfe5-c11e4c1ff9df) |  ![resized_v2_torch float16](https://github.com/pytorch/vision/assets/17803473/8327ba60-904f-4979-8ff3-43f6c9d50d03)

The image I used is from [unsplash](https://unsplash.com/photos/a-man-riding-a-surfboard-on-top-of-a-wave-in-the-ocean-I6FPWd-fi6o).

In v2, when using fp16 I had to convert back to `uint8` without `ConvertImageDtype` otherwise the maximum pixel intensity is `1`.

### Versions

I observed this error in multiple environments (M1 and ubuntu 20.04 with cuda)
```
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (main, Jun 29 2023, 12:23:23) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] hs-infrastructure-flake8-plugins==0.1.2
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.1
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2
```

**Comment by NicolasHug** [comment]
Thanks for the report @antoinebrl 

looking at

```
  torch.float16
    resized,   img.shape=torch.Size([3, 640, 640]), img.dtype=torch.float16, img.min().item()=0.0888671875, img.max().item()=1.0

  torch.float16
    resized,   img.shape=torch.Size([3, 640, 640]), img.dtype=torch.float16, img.min().item()=0.0, img.max().item()=1.0
```

I suspect that what's going on is that V2 always rounds the values. That's a bug that we recently fixed in  https://github.com/pytorch/vision/issues/7667.

Can you try to either

- install the nightly torchvision version and see if the bug is still present
- verify that all float16 values are integers (they shouldn't, that's the bug that was fixed) by calling e.g. `torch.unique`, or checking someting like `(resized_img.round() - resized_img).sum()`

**Comment by antoinebrl** [comment]
I tested the latest nightly build and the problem is gone! v1 and v2 look the same and different dtypes are indistinguishable with human eyes. Thanks  @NicolasHug  for developing the patch!
```
torch              2.1.0.dev20230707
torchvision        0.16.0.dev20230707
```
