### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'float4_e2m1fn_x2'

### ISSUE THREAD

**Issue by IntoLighter** [pytorch/vision#9244]
### 🐛 Describe the bug

Try import torchvision. It was installed with `pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130`.

```python
import torchvision
```

```
AttributeError: module 'torch' has no attribute 'float4_e2m1fn_x2'

Cell In[15], line 4
      2 import torch.nn as nn
      3 import torch.optim as optim
----> 4 import torchvision
      5 import torchvision.transforms as transforms
      7 # --- 1. Загрузка и нормализация данных ---

File ~\AppData\Local\Programs\Python\Python313\Lib\site-packages\torchvision\__init__.py:10
      7 # Don't re-order these, we need to load the _C extension (done when importing
      8 # .extensions) before entering _meta_registrations.
      9 from .extension import _HAS_OPS  # usort:skip
---> 10 from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
     12 try:
     13     from .version import __version__  # noqa: F401

File ~\AppData\Local\Programs\Python\Python313\Lib\site-packages\torchvision\models\__init__.py:3
      1 from .alexnet import *
      2 from .convnext import *
----> 3 from .densenet import *
      4 from .efficientnet import *
      5 from .googlenet import *

File ~\AppData\Local\Programs\Python\Python313\Lib\site-packages\torchvision\models\densenet.py:9
      7 import torch.nn as nn
      8 import torch.nn.functional as F
----> 9 import torch.utils.checkpoint as cp
     10 from torch import Tensor
     12 from ..transforms._presets import ImageClassification

File ~\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\checkpoint.py:15
     13 import torch.fx.traceback as fx_traceback
     14 from torch.utils._pytree import tree_map
---> 15 from torch.testing._internal.logging_tensor import capture_logs, LoggingTensorMode
     16 from torch.utils._python_dispatch import TorchDispatchMode
     18 __all__ = [
     19     "checkpoint",
     20     "checkpoint_sequential",
   (...)     34     "SAC_IGNORED_OPS",
     35 ]

File ~\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\testing\_internal\logging_tensor.py:10
      8 import contextlib
      9 import itertools
---> 10 from torch.utils._dtype_abbrs import dtype_abbrs as _dtype_abbrs
     11 from torch.utils._python_dispatch import TorchDispatchMode
     12 from torch.utils.weak import WeakTensorKeyDictionary

File ~\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\_dtype_abbrs.py:15
      1 import torch
      4 # Used for testing and logging
      5 dtype_abbrs = {
      6     torch.bfloat16: "bf16",
      7     torch.float64: "f64",
      8     torch.float32: "f32",
      9     torch.float16: "f16",
     10     torch.float8_e4m3fn: "f8e4m3fn",
     11     torch.float8_e5m2: "f8e5m2",
     12     torch.float8_e4m3fnuz: "f8e4m3fnuz",
     13     torch.float8_e5m2fnuz: "f8e5m2fnuz",
     14     torch.float8_e8m0fnu: "f8e8m0fnu",
---> 15     torch.float4_e2m1fn_x2: "f4e2m1fnx2",
     16     torch.complex32: "c32",
     17     torch.complex64: "c64",
     18     torch.complex128: "c128",
     19     torch.int8: "i8",
     20     torch.int16: "i16",
     21     torch.int32: "i32",
     22     torch.int64: "i64",
     23     torch.bool: "b8",
     24     torch.uint8: "u8",
     25     torch.uint16: "u16",
     26     torch.uint32: "u32",
     27     torch.uint64: "u64",
     28     torch.bits16: "b16",
     29     torch.bits1x8: "b1x8",
     30 }

File ~\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\__init__.py:2688, in __getattr__(name)
   2685 if name in _lazy_modules:
   2686     return importlib.import_module(f".{name}", __name__)
-> 2688 raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
```

### Versions

Collecting environment information...
C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\cuda\__init__.py:182: UserWarning: cudaGetDeviceCount() returned cudaErrorNotSupported, likely using older driver or on CPU machine (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAFunctions.cpp:88.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 2.9.0+cu130
Is debug build: False
CUDA used to build PyTorch: 13.0
ROCM used to build PyTorch: N/A

OS: Майкрософт Windows 11 Домашняя (10.0.26100 64-разрядная)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 4.0.3
Libc version: N/A

Python version: 3.13.9 (tags/v3.13.9:8183fa5, Oct 14 2025, 14:09:13) [MSC v.1944 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.26100-SP0
Is CUDA available: False
CUDA runtime version: 12.9.86
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU
Nvidia driver version: 576.57
cuDNN version: Could not collect
Is XPU available: False
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Name: 13th Gen Intel(R) Core(TM) i7-13650HX
Manufacturer: GenuineIntel
Family: 198
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 2600
MaxClockSpeed: 2600
L2CacheSize: 11776
L2CacheSpeed: None
Revision: None

Versions of relevant libraries:
[pip3] numpy==2.2.6
[pip3] torch==2.9.0+cu130
[pip3] torchaudio==2.7.1+cu128
[pip3] torchvision==0.24.0+cu130
[conda] Could not collect

**Comment by NicolasHug** [comment]
Thanks for the report @IntoLighter 

Things seem to work on linux:

```
~»conda create -n $env python=3.13 -y && conda activate $env

~» pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130

~ » python
Python 3.13.7 | packaged by Anaconda, Inc. | (main, Sep  9 2025, 19:59:03) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
>>> import torch
>>> torchvision.__version__, torch.__version__
('0.24.0+cu130', '2.9.0+cu130')
```

You're on Windows, which unfortunately makes it difficult to reproduce for us. Let's see if we get more similar reports.

**Comment by IntoLighter** [comment]
The problem was with Windows. I had corrupted files, and update center suggested me to restore the system. I did this and the problem disappeared.
